=== claudioperez/SimCenterExamples/docs/projects/json-schema/input_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Schema for quoFEM ``.json`` input files.",
    "type": "object",
    "title": "quoFEM Schema",
    "properties": {
      "Applications": {
        "type": "object",
        "properties": {
          "UQ": {
            "type": "object",
            "title": "UQ",
            "properties": {
              "Application": { "type": "string" },
              "ApplicationData": {"type": "object", "properties": {} }
            },
            "description": "[incomplete desciption.]",
            "required": [
              "Application",
              "ApplicationData"
            ]
          }
        },
        "required": ["UQ"]
      },
      "EDP": {
        "type": "array",
        "description": "Inputs for the QoI tab.",
        "title": "QoI",
        "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              }
            },
            "required": [
              "name"
            ]
          }
      },
      "UQ_Method": {
        "type": "object",
        "description": "Inputs for the UQ panel.",
        "title": "UQ panel",
        "properties": {
          "uqEngine": {
            "type": "string",
            "title": "UQ Engine",
            "description": "UQ engine.",
            "default": "Dakota"
          },
          "uqType": {
            "type": "string",
            "title":"Dakota Method Category",
            "enum": ["Forward Propagation", "Parameter Estimation", "Inverse Problem", "Reliability Analysis", "Sensitivity Analysis"]
          },
          "samplingMethodData": {
            "type": "object",
            "title": "Forward Propagation",
            "properties": {
              "method":  {"type": "string" , "title": "Method"},
              "samples": {"type": "integer", "title": "Samples"},
              "seed":    {"type": "integer", "title": "Seed"},

              "dataMethod": {"type": "string", "title":"Method for Data Generation", 
                "enum": ["Quadrature", "Smolyak Sparse_Grid", "Stroud Cubature", "Orthogonal Least_Interpolation"]},
              "level": {"type": "integer"},
              
              "samplingMethod":  {"type": "string", "title":"Data Generation Method",
                "enum": ["Monte Carlo", "LHS"]},
              "samplingSamples": {"type": "integer"},
              "samplingSeed":    {"type": "integer"},
              "surrogateSurfaceMethod": {"type": "string", "title":"Surface Fitting Method", 
                "enum": ["mars","gaussian_process surfpack","moving_least_squares","neural_network", "polynomial linear", "polynomial quadratic", "polynomial cubic"]},
              
              "trainingMethod":  {"type": "string", "title":"Data Generation Method",
                "enum": ["Monte Carlo", "LHS"]},
              "trainingSamples": {"type": "integer"},
              "trainingSeed":    {"type": "integer"},

              "ismethod": {"type": "string", 
                "enum":["adapt_import", "import", "mm_adapt_import"]}
            },
            "oneOf": [
              {"properties": {"method": {"enum": ["Gaussian Process Regression"]}},
                "required": [
                  "method",
                  "samplingMethod",
                  "samplingSamples",
                  "samplingSeed",
                  "surrogateSurfaceMethod",
                  "trainingMethod",
                  "trainingSamples",
                  "trainingSeed"]},
              {
                "properties": {"method": {"enum": ["LHS"]}},
                "required": [
                  "method",
                  "samples",
                  "seed"
                ]
              },
              {
                "properties": {"method": {"enum": ["Monte Carlo"]}},
                "required": [
                  "method",
                  "samples",
                  "seed"
                ]
              },
              {
                "properties": {"method": {"enum": ["Polynomial Chaos Expansion"]}},
                "required": [
                  "method",
                  "dataMethod",
                  "level",
                  "samplingMethod",
                  "samplingSeed"
                ]
              },
              {
                "properties": {"method": {"enum": ["Importance Sampling"]}},
                "required": [
                  "samples",
                  "ismethod",
                  "method",
                  "seed"
                ]
              }
            ]
          },
          "reliabilityMethodData": {
            "type": "object",
            "title": "Reliability Analysis",
            "properties":{
              "integrationMethod": {"type": "string", "title": "Integration Method",
                "enum": ["First Order", "Second Order"]},
              "levelType":         {"type": "string", "title": "Level Type",
                "enum": ["Response Levels", "Probability Levels"]},
              "localMethod":       {"type": "string", "title": "Local Method"},
              "method":            {"type": "string", "title": "Reliability Method",
                "enum": ["Global Reliability", "Local Reliability"]},
              "mpp_Method":        {"type": "string", "title": "MPP Search Method",
                "enum": ["no_approx","u_taylor_mpp", "x_taylor_mpp","u_taylor_mean", "x_taylor_mean"]},
              "gpApproximation":   {"type": "string", 
                "enum": ["u-space", "x-space"]},
              "probabilityLevel":  {"type": "array", "title": "Probability Levels"},
              "responseLevel":     {"type": "array", "title": "Response Levels"}
            },
            "oneOf": [
              { "properties": {
                  "method":      {"enum":["Global Reliability"]}},
                "required": [
                  "responseLevel",
                  "method",
                  "gpApproximation"
                ]},
              { "properties": {
                  "method":      {"enum": ["Local Reliability"]},
                  "localMethod": {"enum": ["Mean Value"]}},
                "required": [
                  "method",
                  "levelType",
                  "localMethod"
                ]},
              { "properties": {
                  "method":      {"enum": ["Local Reliability"]},
                  "localMethod": {"enum": ["Most Probable Point"]}},
                "required": [
                  "method",
                  "integrationMethod",
                  "levelType",
                  "localMethod",
                  "mpp_Method"
                ]}
            ]
          },
          "bayesianCalibrationMethodData": {
            "type": "object",
            "title": "Inverse Problem",
            "properties": {
              "burnInSamples": {"type": "number", "title": "No. Burn in Samples"},
              "chainSamples":  {"type": "number", "title": "No. Chain Samples"},
              "chains":        {"type": "number", "title": "No. Chains"},
              "jumpStep":      {"type": "number", "title": "Jump Step"},
              "method":        {"type": "string", "title": "Method",
                                "enum": ["DREAM"]},
              "seed":          {"type": "number", "title": "Seed"}
            }
          },
          "calibrationMethodData": {
            "type": "object",
            "description": "Input data for **Parameter Estimation**.",
            "properties": {
              "convergenceTol": {"type": "number", "title": "Convergence Tol", "description": "Convergence tolerance."},
              "factors":        {"type": "number", "title": "Scaling Factors"},
              "maxIterations":  {"type": "number", "title": "Max No. Iterations"},
              "method":         {"type": "string", "title": "Method",
                                 "enum": ["NL2SOL", "OPT++GaussNewton"]}
            }
          }
        },
        "required": ["uqEngine","uqType"],
        "oneOf": [
          {"properties": {"uqType": {"enum": ["Forward Propagation"]}},
            "required": ["samplingMethodData"]}, 
          {"properties": {"uqType": {"enum": ["Sensitivity Analysis"]}},
            "required": ["samplingMethodData"]}, 
          {"properties": {"uqType": {"enum": ["Reliability Analysis"]}},
           "required": ["reliabilityMethodData"]},
          {"properties": {"uqType": {"enum": ["Inverse Problem"]}},
           "required": ["bayesianCalibrationMethodData"]},
          {"properties": {"uqType": {"enum": ["Parameter Estimation"]}},
           "required": ["calibrationMethodData"]}
        ]
      },
      "fem": {
        "type": "object",
        "description": "Inputs for the FEM tab.",
        "title": "FEM tab",
        "properties": {
          "dir": {
            "type": "string"
          },
          "inputFile": {
            "type": "string",
            "title":"Input File"
          },
          "mainInput": {
            "type": "string"
          },
          "mainPostprocessScript": {
            "type": "string",
            "description": "Path to post-processing script."
          },
          "numInputs":         {"type": "integer"},
          "parametersFile":    {"type": "string"},
          "parametersScript":  {"type": "string"},
          "postprocessScript": {"type": "string"},
          "program":           {"type": "string" }
        },
        "required": [
          "dir",
          "inputFile",
          "mainInput",
          "mainPostprocessScript",
          "numInputs",
          "parametersFile",
          "parametersScript",
          "postprocessScript",
          "program"
        ]
      },
      "localAppDir": {
        "type": "string",
        "description": "[incomplete]"
      },
      "python":  {"type": "string"},
      "randomVariables": {
        "type": "array",
        "title": "RV tab",
        "items": {
          "type": "object",
          "properties": {
            "distribution":  {"type": "string" },
            "name":          {"type": "string" },
            "refCount":      {"type": "integer"},
            "stdDev":        {"type": "number" },
            "value":         {"type": "string" },
            "variableClass": {"type": "string" }
          },
          "required": [
            "distribution",
            "name",
            "refCount",
            "value",
            "variableClass"
          ]
        }
      },
      "remoteAppDir":  {"type": "string"},
      "uqResults":     {"type": "object", "properties":{}},
      "workingDir":    {"type": "string"}
    },
    "required": [
      "Applications",
      "EDP",
      "UQ_Method",
      "fem",
      "localAppDir",
      "python",
      "randomVariables",
      "remoteAppDir",
      "uqResults",
      "workingDir"
    ]
  }

=== claudioperez/SimCenterExamples/quoFEM/03_Rosenbrock/input_forward.json
{
    "Applications": {
        "UQ": {
            "Application": "Dakota-UQ",
            "ApplicationData": {
            }
        }
    },
    "EDP": [
        {
            "name": "f"
        }
    ],
    "UQ_Method": {
        "samplingMethodData": {
            "method": "LHS",
            "samples": 100,
            "seed": 949
        },
        "uqEngine": "Dakota",
        "uqType": "Forward Propagation"
    },
    "fem": {
        "dir": "{Current_Dir}/.",
        "inputFile": "{Current_Dir}/rosenbrock.py",
        "mainInput": "rosenbrock.py",
        "mainPostprocessScript": "",
        "numInputs": 1,
        "parametersFile": "params.py",
        "parametersScript": "{Current_Dir}/params.py",
        "postprocessScript": "",
        "program": "OpenSeesPy"
    },
    "localAppDir": "C:/Tools/quoFEM/quoFEM",
    "python": "python",
    "randomVariables": [
        {
            "distribution": "Uniform",
            "lowerbound": -2,
            "name": "x",
            "refCount": 1,
            "upperbound": 2,
            "value": "RV.x",
            "variableClass": "Uncertain"
        },
        {
            "distribution": "Uniform",
            "lowerbound": 1.4,
            "name": "y",
            "refCount": 1,
            "upperbound": 1.6,
            "value": "RV.y",
            "variableClass": "Uncertain"
        }
    ],
    "remoteAppDir": "/home1/00477/tg457427/SimCenterBackendApplications/May-2020",
    "uqResults": {
    },
    "workingDir": "C:/Workdir/quoFEM"
}

=== claudioperez/SimCenterExamples/_build/quoFEM/archive/quoFEM_Examples/quoFEM_Examples/01_OpenSeesPy_basic/input.json
{
    "Applications": {
        "UQ": {
            "Application": "Dakota-UQ",
            "ApplicationData": {
            }
        }
    },
    "EDP": [
        {
            "name": "Node_2_Disp_2"
        },
        {
            "name": "Node_3_Disp_2"
        }
    ],
    "UQ_Method": {
        "samplingMethodData": {
            "method": "LHS",
            "samples": 200,
            "seed": 553
        },
        "uqEngine": "Dakota",
        "uqType": "Forward Propagation"
    },
    "fem": {
        "dir": "{Current_Dir}/.",
        "inputFile": "{Current_Dir}/TrussTemplate.py",
        "mainInput": "TrussTemplate.py",
        "mainPostprocessScript": "postproc.py",
        "numInputs": 1,
        "parametersFile": "params.py",
        "parametersScript": "{Current_Dir}/params.py",
        "postprocessScript": "{Current_Dir}/postproc.py",
        "program": "OpenSeesPy"
    },
    "localAppDir": "C:/Tools/quoFEM/quoFEM",
    "python": "python",
    "randomVariables": [
        {
            "distribution": "Normal",
            "mean": 205,
            "name": "E",
            "refCount": 1,
            "stdDev": 10,
            "value": "RV.E",
            "variableClass": "Uncertain"
        },
        {
            "distribution": "Normal",
            "mean": 25,
            "name": "P",
            "refCount": 1,
            "stdDev": 10,
            "value": "RV.P",
            "variableClass": "Uncertain"
        },
        {
            "distribution": "Normal",
            "mean": 250,
            "name": "Ao",
            "refCount": 1,
            "stdDev": 10,
            "value": "RV.Ao",
            "variableClass": "Uncertain"
        },
        {
            "distribution": "Normal",
            "mean": 500,
            "name": "Au",
            "refCount": 1,
            "stdDev": 10,
            "value": "RV.Au",
            "variableClass": "Uncertain"
        }
    ],
    "remoteAppDir": "/home1/00477/tg457427/SimCenterBackendApplications/May-2020",
    "uqResults": {
    },
    "workingDir": "C:/Workdir/quoFEM"
}
